# App Password can be created in the user settings (Directory -> Token and App Passwords)

@username=john
@app_password=nt7su3vuTaxtsmKdlhr2RCbRD4tis5i7zBFJbbTWyeTjrRqTpQ513z73ZlV3
@client_id=hitec_api_client


###
POST https://authentik.szut.dev/application/o/token/
Content-Type: application/x-www-form-urlencoded

grant_type = client_credentials &
username = {{username}} &
password = {{app_password}} &
client_id = {{client_id}} &
scope = openid

###
# curl -X POST "https://authentik.szut.dev/application/o/token/";
#  -H "Content-Type: application/x-www-form-urlencoded"
#  -d "grant_type=client_credentials"
#  -d "username=john"
#  -d "password=nt7su3vuTaxtsmKdlhr2RCbRD4tis5i7zBFJbbTWyeTjrRqTpQ513z73ZlV3"
#  -d "client_id=hitec_api_client"
#  -d "scope=openid"



